[package]
name = "screeps_arena_sim"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libloading = "0.8"
anyhow = "1.0"
mock-screeps-arena = { path = "../arena_api_mock/mock-screeps-arena" }
sha2 = "0.10"
fastrand = "2.0"
libc = "0.2"
log = "0.4"
env_logger = "0.10"
